#--- Variables --------------------------------------------------------------------------------------------
PROJECT_NAME = Smoggle
VERSION      = 1.5.0
DESCRIPTION  = Multidimensional and multilanguage Boggle solver
AUTHORS      = Nicolas Lermé
LICENSE      = LGPL-v3
LAST_RELEASE = `date`
